// Class: ReadMLPBNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBNN
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.24/02       [399362]
Creator        : sofiastrazzi
Date           : Tue Sep  7 19:19:01 2021
Host           : Darwin HMBRW-A-001-M1-005.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May 8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64
Dir            : /Users/sofiastrazzi/Documents/SOFT_AND_COMP/ESAME/Software_and_Computing_Exam
Training events: 466027
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "60" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
EventNumber                   EventNumber                   EventNumber                   EventNumber                                                     'F'    [0,624]
MET                           MET                           MET                           MET                                                             'F'    [4.62389932658e-14,745.451171875]
jet_pT                        jet_pT                        jet_pT                        jet_pT                                                          'F'    [-2.52659320831,1793.88195801]
jet_eta                       jet_eta                       jet_eta                       jet_eta                                                         'F'    [-5.95245170593,6.01675987244]
jet_phi                       jet_phi                       jet_phi                       jet_phi                                                         'F'    [-3.1415913105,3.1415886879]
jet_m                         jet_m                         jet_m                         jet_m                                                           'F'    [-8.35758328321e-05,231.484832764]
jet_isB                       jet_isB                       jet_isB                       jet_isB                                                         'F'    [0,1]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBNN : public IClassifierReader {

 public:

   // constructor
   ReadMLPBNN( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLPBNN" ),
        fNvars( 7 )
   {
      // the training input variables
      const char* inputVars[] = { "EventNumber", "MET", "jet_pT", "jet_eta", "jet_phi", "jet_m", "jet_isB" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][7];
   double fScal_1[3][7];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[13][8];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][13];   // weight matrix from layer 1 to 2

};

inline void ReadMLPBNN::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.586790989359619;
   fWeightMatrix0to1[1][0] = 2.20126790315327;
   fWeightMatrix0to1[2][0] = 0.654958488140345;
   fWeightMatrix0to1[3][0] = 1.89276407746769;
   fWeightMatrix0to1[4][0] = -3.0331556024349;
   fWeightMatrix0to1[5][0] = -0.0340748563770417;
   fWeightMatrix0to1[6][0] = -0.63326640465284;
   fWeightMatrix0to1[7][0] = 2.61389903816412;
   fWeightMatrix0to1[8][0] = -0.789307936974181;
   fWeightMatrix0to1[9][0] = -0.753191193153895;
   fWeightMatrix0to1[10][0] = -1.27339898231326;
   fWeightMatrix0to1[11][0] = -0.446922513101526;
   fWeightMatrix0to1[0][1] = -1.45358851200675;
   fWeightMatrix0to1[1][1] = 0.373817212218945;
   fWeightMatrix0to1[2][1] = 0.127579481798779;
   fWeightMatrix0to1[3][1] = 0.578676672944653;
   fWeightMatrix0to1[4][1] = 0.0574584190380522;
   fWeightMatrix0to1[5][1] = 5.2959585096816;
   fWeightMatrix0to1[6][1] = 0.266955998069466;
   fWeightMatrix0to1[7][1] = 0.770399431930946;
   fWeightMatrix0to1[8][1] = 1.45279332192446;
   fWeightMatrix0to1[9][1] = -1.0224388810156;
   fWeightMatrix0to1[10][1] = 1.55956395221192;
   fWeightMatrix0to1[11][1] = 0.0802812020614188;
   fWeightMatrix0to1[0][2] = -1.42734825696734;
   fWeightMatrix0to1[1][2] = 0.496672490591267;
   fWeightMatrix0to1[2][2] = 1.60093826703156;
   fWeightMatrix0to1[3][2] = -1.19986526315851;
   fWeightMatrix0to1[4][2] = -2.15328349850892;
   fWeightMatrix0to1[5][2] = 0.685471053684768;
   fWeightMatrix0to1[6][2] = 0.811919388951318;
   fWeightMatrix0to1[7][2] = 1.0867081213105;
   fWeightMatrix0to1[8][2] = -0.0450098570110681;
   fWeightMatrix0to1[9][2] = -0.363701773508115;
   fWeightMatrix0to1[10][2] = 0.584876288937155;
   fWeightMatrix0to1[11][2] = -0.303568324255134;
   fWeightMatrix0to1[0][3] = -1.43221785042727;
   fWeightMatrix0to1[1][3] = 1.51249979127652;
   fWeightMatrix0to1[2][3] = -0.898945719753626;
   fWeightMatrix0to1[3][3] = 1.27037765012216;
   fWeightMatrix0to1[4][3] = 0.61226396490102;
   fWeightMatrix0to1[5][3] = 0.176845527304209;
   fWeightMatrix0to1[6][3] = 1.80732956545473;
   fWeightMatrix0to1[7][3] = 1.27279514642963;
   fWeightMatrix0to1[8][3] = -0.994653461510106;
   fWeightMatrix0to1[9][3] = -0.692190946661308;
   fWeightMatrix0to1[10][3] = 0.329141448131478;
   fWeightMatrix0to1[11][3] = 0.0716172242907195;
   fWeightMatrix0to1[0][4] = 1.26550088557858;
   fWeightMatrix0to1[1][4] = 0.978528021594435;
   fWeightMatrix0to1[2][4] = 0.334995772059261;
   fWeightMatrix0to1[3][4] = 1.13308467909933;
   fWeightMatrix0to1[4][4] = -1.71065332918074;
   fWeightMatrix0to1[5][4] = 0.0874654122471566;
   fWeightMatrix0to1[6][4] = -1.70784820348629;
   fWeightMatrix0to1[7][4] = -0.614863197588452;
   fWeightMatrix0to1[8][4] = -1.1657654530686;
   fWeightMatrix0to1[9][4] = -0.27507185871647;
   fWeightMatrix0to1[10][4] = 0.563849007744106;
   fWeightMatrix0to1[11][4] = 0.653867238377422;
   fWeightMatrix0to1[0][5] = -1.81599612893575;
   fWeightMatrix0to1[1][5] = 1.05387343213365;
   fWeightMatrix0to1[2][5] = -0.188290354847702;
   fWeightMatrix0to1[3][5] = 0.575007334922871;
   fWeightMatrix0to1[4][5] = 1.58700578286601;
   fWeightMatrix0to1[5][5] = 0.233618970549866;
   fWeightMatrix0to1[6][5] = 0.250525923991537;
   fWeightMatrix0to1[7][5] = -1.71904666491851;
   fWeightMatrix0to1[8][5] = 1.02396119209633;
   fWeightMatrix0to1[9][5] = -1.01500642513609;
   fWeightMatrix0to1[10][5] = -0.386770471652478;
   fWeightMatrix0to1[11][5] = -1.45159853980889;
   fWeightMatrix0to1[0][6] = 0.477904862270784;
   fWeightMatrix0to1[1][6] = 1.14903182312284;
   fWeightMatrix0to1[2][6] = 2.72314648274322;
   fWeightMatrix0to1[3][6] = -0.3923549439892;
   fWeightMatrix0to1[4][6] = -1.18777413122366;
   fWeightMatrix0to1[5][6] = -4.86912807247819;
   fWeightMatrix0to1[6][6] = 1.18959388374484;
   fWeightMatrix0to1[7][6] = -0.404609290537617;
   fWeightMatrix0to1[8][6] = 0.950953031862867;
   fWeightMatrix0to1[9][6] = 1.26500768850728;
   fWeightMatrix0to1[10][6] = 1.81398045297368;
   fWeightMatrix0to1[11][6] = -0.782597763711023;
   fWeightMatrix0to1[0][7] = -0.600121428540173;
   fWeightMatrix0to1[1][7] = -0.976105879489694;
   fWeightMatrix0to1[2][7] = 1.18373064197183;
   fWeightMatrix0to1[3][7] = -1.02799532136231;
   fWeightMatrix0to1[4][7] = -1.14695801167122;
   fWeightMatrix0to1[5][7] = 1.31459004443119;
   fWeightMatrix0to1[6][7] = -0.352363787472082;
   fWeightMatrix0to1[7][7] = 0.48591260096884;
   fWeightMatrix0to1[8][7] = 2.36661261467406;
   fWeightMatrix0to1[9][7] = -2.17940961495795;
   fWeightMatrix0to1[10][7] = -1.0564787396734;
   fWeightMatrix0to1[11][7] = 1.64380154360586;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.198446070947039;
   fWeightMatrix1to2[0][1] = -1.14464422118457;
   fWeightMatrix1to2[0][2] = -2.01778384061603;
   fWeightMatrix1to2[0][3] = 0.663113131324626;
   fWeightMatrix1to2[0][4] = -0.890256839472987;
   fWeightMatrix1to2[0][5] = -4.03194909421056;
   fWeightMatrix1to2[0][6] = 0.0147215379425852;
   fWeightMatrix1to2[0][7] = 1.71075992198341;
   fWeightMatrix1to2[0][8] = -0.782023752024647;
   fWeightMatrix1to2[0][9] = 1.02539858434793;
   fWeightMatrix1to2[0][10] = -1.49348659679983;
   fWeightMatrix1to2[0][11] = -0.35000162619545;
   fWeightMatrix1to2[0][12] = 0.385634061130446;
}

inline double ReadMLPBNN::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)7) {
      std::cout << "Input vector needs to be of size " << 7 << std::endl;
      return 0;
   }

   std::array<double, 13> fWeights1 {{}};
   std::array<double, 1> fWeights2 {{}};
   fWeights1.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<12; o++) {
      std::array<double, 8> buffer; // no need to initialise
      for (int i = 0; i<8 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][7];
      for (int i=0; i<8; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<12; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<1; o++) {
      std::array<double, 13> buffer; // no need to initialise
      for (int i=0; i<13; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<13; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights2[o] = OutputActivationFnc(fWeights2[o]);
   } // loop over o

   return fWeights2[0];
}

double ReadMLPBNN::ActivationFnc(double x) const {
   // fast hyperbolic tan approximation
   if (x > 4.97) return 1;
   if (x < -4.97) return -1;
   float x2 = x * x;
   float a = x * (135135.0f + x2 * (17325.0f + x2 * (378.0f + x2)));
   float b = 135135.0f + x2 * (62370.0f + x2 * (3150.0f + x2 * 28.0f));
   return a / b;
}
double ReadMLPBNN::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLPBNN::Clear()
{
}
inline double ReadMLPBNN::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform_1()
{
   double fMin_1[3][7];
   double fMax_1[3][7];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 624;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 104;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 624;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 5.86157695732e-13;
   fMax_1[0][1] = 745.451171875;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 4.62389932658e-14;
   fMax_1[1][1] = 641.649475098;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 4.62389932658e-14;
   fMax_1[2][1] = 745.451171875;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = -1.35159313679;
   fMax_1[0][2] = 1793.88195801;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = -2.52659320831;
   fMax_1[1][2] = 966.75189209;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = -2.52659320831;
   fMax_1[2][2] = 1793.88195801;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = -5.80716943741;
   fMax_1[0][3] = 6.01675987244;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = -5.95245170593;
   fMax_1[1][3] = 5.94509124756;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = -5.95245170593;
   fMax_1[2][3] = 6.01675987244;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = -3.14158296585;
   fMax_1[0][4] = 3.1415886879;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = -3.1415913105;
   fMax_1[1][4] = 3.1415746212;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = -3.1415913105;
   fMax_1[2][4] = 3.1415886879;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 1.90734863281e-06;
   fMax_1[0][5] = 190.149215698;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = -8.35758328321e-05;
   fMax_1[1][5] = 231.484832764;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = -8.35758328321e-05;
   fMax_1[2][5] = 231.484832764;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 1;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 1;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 1;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 7;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<7;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
